routes/web.php
<?php

use App\Models\section;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\SectionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('sections',SectionController::class);
Route::resource('books',BookController::class);
Route::resource('authors',AuthController::class);
/*Route::get('/', function () {
    return view('welcome');
});*/

app/Models/Book.php
<?php

namespace App\Models;

use App\Models\Author;
use Illuminate\Database\Eloquent\Model;
use App\Models\book_author;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Book extends Model
{
    protected $fillable = [
        'title',
        'description',
        'edition',
        'publication',
        
    ];
   
    use HasFactory;
    public function authors()
    {
        return $this->belongsToMany(Author::class,'book_author');//book_author is the table name
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;
use App\Models\Book;
use App\Models\Author;
use App\Models\Section;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { $book['books'] =Book::orderBy('id','desc');
        return view('books.index', $book);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    { 
     /*  $request->validate([
        'title'=>'required',
        'edition'=>'required',
        'description'=>'required',
        'publication'=>'required',
       ]);
        $book = new Book();
        $book->title =  $request->title;
        $book->edition =  $request->edition;
        $book->description =  $request->description;
        $book->publication =  $request->publication;
        $book->section_id =  $request->section_id;
        $book->save();
       $section['section'] =Section::findOrFail($request->section_id);
    return redirect()->route('sections.show',$section)->with('succes','your book added successeffuly');
    */
    $author_id =1;
    $request->validate([
        'title'=>'required',
        'edition'=>'required',
        'description'=>'required',
        'publication'=>'required',
       ]);
      $author2 =$request->other_auther; 
      if(!empty($author2))
     { $auther2_id=Author::where('first_name',$author2)->first();
    // dd($auther2_id) ; 
}
      $book = new Book();
        $book->title =  $request->title;
        $book->edition =  $request->edition;
        $book->description =  $request->description;
        $book->publication =  $request->publication;
        $book->section_id =  $request->section_id;
         $book->save();
     //var_dump($auther2_id);die;
     if(!empty($author2_id))
         { DB::table('book_author')->insert([
    ['author_id' => $author_id, 'book_id'=>$book->id],
    ['author_id' => $auther2_id->id, 'book_id'=>$book->id],
]);

         }
         else
            { 
                DB::table('book_author')->insert([
                ['author_id' => $author_id, 'book_id'=>$book->id],
            ]);
         }
    
       $section['section'] =Section::findOrFail($request->section_id);
    return redirect()->route('sections.show',$section)->with('succes','your book added successeffuly');

}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(  $id)
    {
       
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Book $book)
    {
       $request->validate([
            'title'=>'required',
            'edition'=>'required',
            'description'=>'required',
            'publication'=>'required',
           ]);
        
            $book->title =  $request->title;
            $book->edition =  $request->edition;
            $book->description =  $request->description;
            $book->publication =  $request->publication;
            $book->section_id =  $request->section_id;
            $book->save();
          // $section['section'] =Section::findOrFail($request->section_id);
        return redirect()->route('sections.show',$book->section_id)->with('succes','your book added successefully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Book $book)
    { 
        
       $section['section'] = Section::findOrFail($book->section_id);
       //dd($section);
       DB::table('book_author')->where('book_id',$book->id)->delete();
       $book->delete();
      
       
        return redirect()->route('sections.show',$section)->with('succes','your book deleted successfuly');
    }
}

resources/views/books/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
  
<div class="container">

    <div class="row" class="p-4">
        @if(session('succes'))
       <div class="alert alert-success" role="alert">
       {{session('succes')}}
</div>
        @endif
    </div>
  <h1>{{$section->section_name}}</h1>  
  <br>
  <br>
    <form action="{{route('books.store')}}" method="post">
        @csrf 
        <input type="hidden" name="section_id" value="{{$section->id}}">
<table class="table">
<tr>
    <td> <label for="">Title</label></td>
<td><input type="text" name='title'></td>
</tr>
<tr>
    <td> <label for="">Edition</label></td>
<td><input type="text" name="edition"></td>
</tr>
<tr>
    <td> <label for="">Publication</label></td>
<td><input type="text" name="publication"></td>
</tr>
<tr>
    <td> <label for="">Description</label></td>
<td><input type="text" name="description"></td>

</tr>
<tr>
    <td> <label for="">Other Author</label></td>
<td><select name="author"class="form-select" aria-label="Default select example">
    <option selected>Open this select menu</option>
   @foreach ($author as $auth)
       
  
    <option value="{{$auth->id}}">{{$auth->first_name.''.$auth->last_name}}</option>
    @endforeach

  </select>
</td>
</tr>
<tr><td><button class="btn btn-primary" > <a  href="{{route('authors.create')}}"   > </a>Add Author</button></td>
</tr>

<tr><td> <button type= "submit" class="btn btn-primary">Add</button></td></tr>
</table>
</form>
@php
  $i= 0;  
@endphp
<table  class="table">
    <th>Title</th>
    <th>Editon</th>
    <th>Description</th>
    <th>Publication</th>
    <th>Author</th>
    <th>Edit</th>
    <th>Delete</th>
@foreach( $all_book as $book)


    <tr>
        <form action="{{ route('books.update', $book->id )}}" method="post">
            @csrf 
            @method('PUT')
            <input type="hidden" value="{{$book->section_id}}">
        <td><input type="text" name="title" value="{{$book->title}}"></td>
        <td><input type="text" name="edition" value="{{$book->edition}}"></td>
        <td><input type="text" name="description" value="{{$book->description}}"></td>
        <td><input type="text" name="publication" value="{{$book->publication}}"></td>
        <td>
        @foreach ($array_of_author[$i] as $author)
           <p> {{$author->last_name}} </p>
           
        @endforeach
        @php
        $i++;
    @endphp
</td>
 <td><button type="submit" class="btn btn-primary" >Edit</button> </td>   
 </form>
 <td><form action="{{ route('books.destroy', $book->id )}}" method="post">
    @csrf 
    @method('DELETE')

 <button type="submit" class="btn btn-primary" >Delete</button>    
 </form>
</td>
</td>
</tr>
</table>

@endforeach
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>