routes/web.php
<?php

use App\Models\section;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\SectionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('sections',SectionController::class);
Route::resource('books',BookController::class);
Route::resource('authors',AuthController::class);
/*Route::get('/', function () {
    return view('welcome');
});*/

app/Models/Section.php
<?php

namespace App\Models;

use App\Models\Book;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Section extends Model
{
    use HasFactory;

    public function books()
    {
     return  $this->hasMany(Book::class);
    }
}

app/Http/Controllers/SectionController.php
<?php

namespace App\Http\Controllers;
use App\Models\Section;
use App\Models\Author;
use App\Models\Book;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $section['sections'] =  Section::orderBy('id','desc')->paginate(5);
     
        //dd(gettype($section));
          return view('sections.index',$section);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    { 
    /* $all_book= DB::table('sections')->join('books','sections.id','=','books.section_id')
     ->where('sections.id',$section->id)->get();*/
     $all_book = $section->books;
    $i=0;
    $array_of_author=[];
     foreach($all_book as $book)
     {
         $array_of_author= Arr::add( $array_of_author,$i,$book->authors()->select('first_name','last_name','author_id')->get());
       $i++;
     }
     //return $array_of_author;
     $author=Author::all();
        return view('books.index',compact('section',$section,'all_book',$all_book,'array_of_author',$array_of_author,'author',$author));//the name of value($array_of_author) must be the same like the key 'array_of_author' value
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/sections/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
  
<div class="container">
    <div class="row" class="p-4"></div>
<h1>Section</h1>
    <table class="table table-striped table-hover">
        <th>Section Name</th>
        <th>Total books</th>
        <th>Update</th>
        <th>Delete</th>
        <th>Show</th>
        @foreach($sections as $section)

   <tr><td><input type="text" name="section_name" value="{{$section->section_name}}"></td>
<td><label for="" name="total_books"value="{{$section->book_total}}"><span class="badge bg-secondary">{{$section->book_total}}</span></label></td>
<td> <button type="submit" class="btn btn-primary" >Update</button></td>
<td> <button type="submit" class="btn btn-danger">Delete</button></td>
<td><a href="{{route('sections.show', compact('section'))}}"> <button type="submit" class="btn btn-secondary">Show</button></a></td>
</tr>
@endforeach
    </table>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>