routes/web.php
<?php

use App\Models\section;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\SectionController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('sections',SectionController::class);
Route::resource('books',BookController::class);
Route::resource('authors',AuthController::class);
/*Route::get('/', function () {
    return view('welcome');
});*/

app/Models/Author.php
<?php

namespace App\Models;

use App\Models\Book;
use Illuminate\Database\Eloquent\Model;
use App\Models\book_author_relationship;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Author extends Model
{
    use HasFactory;

    protected $fillable = [
        'first_name',
        'last_name',
        'address',
        'DOB',
        
    ];
   /* public function books()
    {
        return  this->belongsToMany(Book::class);
    }*/
}

resources/views/authors/author.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <title>Document</title>
</head>
<body>
    <h1>Author</h1>
    <form action="{{ route('authors.store') }}" method="post">
    @csrf
        <table class="table">
       
        <tr>
            <td><label for="">First Name</label></td>
            <td><input type="text" name="first_name"></td>
            
        </tr>
        <tr>
            <td><label for="">Last Name</label></td>
            <td><input type="text" name="last_name"></td>
            
        </tr>
        <tr>
            <td><label for="">Address</label></td>
            <td><input type="text" name="address"></td>
            
        </tr>
        <tr>
            <td><label for="">Date of Birth</label></td>
            <td><input type="date" name="DOB"></td>
            
            
        </tr>
<tr><td><button type="submit" class="btn btn-primary">Add</button></td></tr>
    </table>

</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>